from playwright.sync_api import sync_playwright
import os

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.on("console", lambda msg: print(f"BROWSER CONSOLE: {msg.text}"))
        
        print("Navigating to http://localhost:3000...")
        page.goto("http://localhost:3000")
        
        # Verify page loaded
        print("Checking page title...")
        if "Midscene" not in page.title() and "Vite" not in page.title():
             print(f"Page title might be wrong: {page.title()}")
        
        # Locate Upload Zone
        print("Waiting for upload zone...")
        upload_zone = page.locator("text=点击或拖拽上传测试用例 Excel")
        upload_zone.wait_for()
        
        # Prepare file path
        file_path = os.path.abspath("test_cases.xlsx")
        print(f"Uploading file: {file_path}")
        
        # Click and handle file chooser
        with page.expect_file_chooser() as fc_info:
            upload_zone.click()
        file_chooser = fc_info.value
        file_chooser.set_files(file_path)
        
        print("File uploaded. Waiting for analysis...")
        
        # Wait for "Review" step
        # We can look for the "开始批量执行" button or "Open Baidu" text
        try:
            # Wait up to 60s for AI generation
            page.locator("text=Open Baidu").wait_for(timeout=60000)
            print("SUCCESS: Found 'Open Baidu' test case in list!")
            
            # Check for generated YAML content
            page.locator("text=Generated by DeepSeek").wait_for()
            print("SUCCESS: Found 'Generated by DeepSeek' badge!")
            
        except Exception as e:
            print(f"FAILED to find expected content: {e}")
            page.screenshot(path="frontend_verify_fail.png")
            raise e
            
        browser.close()
        print("Frontend Verification Passed!")

if __name__ == "__main__":
    run()
