# Generated by Django 6.0.1 on 2026-01-23 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Test Case ID from Excel', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Test Case Title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Test Case Description')),
                ('preconditions', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(help_text='Raw steps from Excel')),
                ('expected_result', models.TextField(help_text='Expected result from Excel')),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('total_cases', models.IntegerField(default=0)),
                ('passed_cases', models.IntegerField(default=0)),
                ('failed_cases', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml_content', models.TextField(help_text='Generated YAML content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script', to='workflow.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('log_content', models.TextField(blank=True, help_text='Execution logs')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.testcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workflow.testrun')),
            ],
        ),
    ]
